# Generated by Django 3.2.9 on 2021-11-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Book title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('written_year', models.IntegerField(verbose_name='Book written year')),
                ('birth_year', models.IntegerField(verbose_name='Author birth year')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title', 'author'],
                'unique_together': {('title', 'author')},
            },
        ),
    ]
